### ISSUE TITLE
Just things in readme.md

### ISSUE THREAD

**Issue by osauzet** [cquest/mastodon-munin-plugins#2]
In the README.md of munin plugin, a small mistake  : ln -s $PWD/plugins-conf.d/mastodon /etc/munin/plugin-conf.d/

This directory exist : plugin-conf.d but not this one plugins-conf.d

Thanks for your plugin :-)

**Comment by cquest** [comment]
Fixed in https://github.com/cquest/mastodon-munin-plugins/commit/ffc0446cfd6c08b8aa13dc58ee907f408ad0af5b
